### Make a move (example: e2 -> e4)
@gameId = 1

POST http://localhost:8080/games/{{gameId}}/move
Content-Type: application/json

{
  "from": "e2",
  "to": "e4"
}

### Pawn promotion
POST http://localhost:8080/games/{{gameId}}/move
Content-Type: application/json

{
  "from": "e7",
  "to": "e8",
  "promotion": "queen"
}
